preset: symfony

enabled:
  - short_array_syntax
  - newline_after_open_tag
  - ordered_use
  - php_unit_construct
  - php_unit_strict
  - strict
  - strict_param

finder:
  exclude:
    - "tests"
  not-path:
    - "src/Fixers.php"
  not-name:
    - "*.php.twig"
