language: php

php: 5.6

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: ./fixers check
