language: php

php: 5.6

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

# Nightly builded with https://nightli.es/
# See also: https://github.com/travis-ci/travis-ci/issues/582#issuecomment-124136045
script: ./fixers check
